# Generated by Django 4.0.1 on 2022-01-13 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sex', models.BooleanField()),
                ('age', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('intro', models.TextField(max_length=200)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family_api.relationship')),
            ],
        ),
    ]
