# Generated by Django 3.2.9 on 2021-11-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=60)),
                ('fields', models.CharField(max_length=60)),
                ('official_website', models.CharField(max_length=1000)),
            ],
        ),
    ]
